### ISSUE TITLE
Fail at github action environment

### ISSUE THREAD

**Issue by jackalcooper** [cnstr/apt-parser#1]
after the request success, it crashes at `new Release(data)` and doesn't raise with meaningful info.
failure log: https://github.com/jackalcooper/apt-release-parse/runs/5282848449?check_suite_focus=true
source: https://github.com/jackalcooper/apt-release-parse/pull/6/files

**Comment by tale** [comment]
Yeah, sorry about the cryptic error messages. I'll get to fixing that ASAP. The reason it crashes is most likely from lack of a required field based on what the Debian documentation says.

**Comment by tale** [comment]
Update to the latest version, it should throw proper errors, so I would recommend using a try/catch statement.
